# Generated by Django 4.2.7 on 2023-12-06 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_quiz', '0005_alter_survey_option1_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='respondents',
            field=models.ManyToManyField(blank=True, related_name='surveys_responded', to=settings.AUTH_USER_MODEL),
        ),
    ]
